// Auto-generated by OpenLane
module OFB(
`ifdef USE_POWER_PINS
  inout VPWR,
  inout VGND,
`endif
  input[63:0] data_in,
  input[127:0] key,
  input[63:0] iv,
  input clk,
  input reset,
  output[63:0] data_out
);
endmodule
